# Generated by Django 3.1.3 on 2020-12-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201217_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='heading0_content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='heading1_content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='heading2_content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_0',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_1',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_2',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='heading1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='heading2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
