# Generated by Django 3.1.3 on 2021-01-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210103_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
