# Generated by Django 3.1.3 on 2021-01-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-created_on',)},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='publish',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
