# Generated by Django 3.1.3 on 2020-12-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=150)),
                ('state', models.CharField(default='', max_length=160)),
                ('zip_code', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
